# Generated by Django 4.2.14 on 2024-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$s841A8BkY6NKL4113RvCQD$ydmevFsHKQ+6XkNoiQ3Z09CRZN5JFQGLEYZg3UFzApc=', max_length=10),
        ),
    ]
