# Generated by Django 4.2.14 on 2024-08-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$cjJXWqEGGusOi1Fv67ekgy$g9LqOBFPiobsOu/XyGlWOdxHUobdLeGTYCylaseJZiU=', max_length=10),
        ),
    ]
