services:
  db:
    container_name: data_base
    image: postgres:17-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ft_transcendence

  be:
    container_name: back_end
    build: ./srcs/Back_end/.
    image: back-end:ipman
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${PWD}/srcs/Back_end:/app
    networks:
      - ft_transcendence
 
  frontend:
    container_name: frontend
    build: srcs/Front_end/
    image: frontend:aamhamdi
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ${PWD}/srcs/Front_end:/app
    networks:
      - ft_transcendence
    environment:
      VITE_API_URL: "http://localhost:8000/"

volumes:
  pgdata:

networks:
  ft_transcendence:
    driver: bridge