
services:
  be:
    build:
      context: ./srcs/Back_end/
      dockerfile: Dockerfile
    environment:
      - PYCHARM_HOST=host.docker.internal
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=ft_transcendence.settings
    volumes:
      - ${PWD}/srcs/Back_end/ft_transcendence:/app
    ports:
      - "8000:8000"
      - "5678:5678"  # for debugger
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
  

  frontend:
    container_name: frontend
    build: srcs/Front_end/
    image: frontend:aamhamdi
    restart: always
    volumes:
      - ${PWD}/srcs/Front_end:/app
    networks:
      - ft_transcendence
    environment:
      - VITE_API_URL=https://${HOSTNAME}:1024/
      - VITE_SOCKET_URL=wss://${HOSTNAME}:1024/