services:
  vault:
    container_name: vault
    image: vault:ipman
    build: ./srcs/vault/.
    volumes:
      - ./vault/file:/vault/file
      - vault-data:/vault/data
    ports:
      - "8200:8200"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - ft_transcendence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://vault:8200/v1/sys/health"]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    container_name: database
    build: ./srcs/database/
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    depends_on:
      - vault
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./srcs/database/init.sql:/docker-entrypoint-init/db.d/init.sql
    networks:
      - ft_transcendence

  be:
    container_name: back_end
    build: ./srcs/Back_end/.
    image: back-end:ipman
    restart: always
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ${PWD}/srcs/Back_end:/app
    networks:
      - ft_transcendence


  frontend:
    container_name: frontend
    build: srcs/Front_end/
    image: frontend:aamhamdi
    restart: always
    volumes:
      - ${PWD}/srcs/Front_end:/app
    networks:
      - ft_transcendence
    environment:
      - VITE_API_URL=https://${HOSTNAME}:1024/
      - VITE_SOCKET_URL=wss://${HOSTNAME}:1024/
      - VITE_EMOJIES_API=https://emoji-api.com/
      - VITE_EMOJIES_KEY="access_key=5f603eacb5994ec1a691d954ed1b809c369c465d"
      - API_URL=https://${HOSTNAME}:1024/
      - EMOJIES_API=https://emoji-api.com/
      - EMOJIES_KEY=access_key=64cbbf2e3c845a7633199a3004eefb71c5eaf31a


  nginx:
    container_name: nginx
    image: nginx:ipman
    build: ./srcs/nginx/.
    restart: always
    ports:
      - "8080:80"
      - "1024:443"
    networks:
      - ft_transcendence
    depends_on:
      - vault
      - be
    environment:
      - WAIT_FOR_IT_TIMEOUT=60



volumes:
  vault-data:
    driver : local
  pgdata:
    driver : local

networks:
  ft_transcendence:
    driver: bridge
