version : "3.7"

networks:
  Net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  db:
    container_name: data_base
    build: ./srcs/Data_Base/.
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 133742
      POSTGRES_USER: ipman
      POSTGRES_DB: ft_transcendence
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      Net:
        ipv4_address: 172.20.0.3

  be:
    container_name: back_end
    build: ./srcs/Back_end/.
    restart : always
    # volumes:
    #   - srcs/Back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      Net:
        ipv4_address: 172.20.0.2
    
