version : "3.7"

networks:
  Net:

services:
  db:
    container_name: data_base
    build: ./srcs/Data_Base/.
    restart: always
    environment:
      POSTGRES_PASSWORD: 133742
      POSTGRES_USER: ipman
      POSTGRES_DB: ft_transcendence
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - Net
  be:
    container_name: back_end
    build: ./srcs/Back_end/.
    restart : always
    # volumes:
    #   - srcs/Back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - Net
    
