version : "3.7"

services:
  DB:
    container_name: postgres
    build: ./srcs/Data_Base/.
    image: postgres:mel-harc42
    env_file:
      - .env
    ports:
      - "5432:5432"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf' -h localhost
    volumes:
      - /var/run/postgresql:/var/run/postgresql

