version: '3.4'

services:
  be:
    build:
      context: ./srcs/Back_end/
      dockerfile: Dockerfile.debug
    environment:
      - PYCHARM_HOST=host.docker.internal
      - DEBUG=True
    volumes:
      - ${PWD}/srcs/Back_end/ft_transcendence:/app
    ports:
      - "8000:8000"
      - "5678:5678"  # for debugger
    # RUN bash with interactive mode
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000