
networks:
  ft_transcendence:
    driver: bridge

services:
  db:
    container_name: data_base
    build: ./srcs/Data_Base/.
    image: data-base:ipman
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      ft_transcendence:

  be:
    container_name: back_end
    build: ./srcs/Back_end/.
    image: back-end:ipman
    restart : always
    ports:
      - "8000:8000"
    depends_on:
      db :
        - "health_service"
    volumes:
      - ${PWD}/srcs/Back_end:/app
    networks:
      ft_transcendence:
    
  frontend:
    container_name: frontend
    build: srcs/Front_end/
    image: frontend:aamhamdi
    restart : always
    ports:
      - 5173:5173
    volumes:
      - ${PWD}/srcs/Front_end:/app
    networks:
      - ft_transcendence

