# Generated by Django 4.2.14 on 2024-09-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
