# Generated by Django 4.2.14 on 2024-09-10 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_is_blocked_remove_message_is_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation_id',
            new_name='conversation',
        ),
    ]
