# Generated by Django 4.2.14 on 2024-09-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
