# Generated by Django 4.2.14 on 2024-09-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_rename_text_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='start_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='initiator',
            new_name='sender',
        ),
    ]
