# Generated by Django 4.2.14 on 2024-09-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='last_message_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
