# Generated by Django 4.2.14 on 2024-09-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_conversation_last_message_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-last_message_time',)},
        ),
    ]
