# Generated by Django 4.2.14 on 2024-08-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.FloatField(default=0.0),
        ),
    ]
