DROP ROLE IF EXISTS root;
CREATE ROLE root WITH LOGIN PASSWORD '133742';
CREATE DATABASE root;
GRANT ALL PRIVILEGES ON DATABASE root TO root;
CREATE USER ipman WITH PASSWORD '133742';
CREATE DATABASE ft_transcendence;
GRANT ALL PRIVILEGES ON DATABASE ft_transcendence TO ipman;